### PR TITLE
Remove Shipment Address required values

### LINKED ISSUE #703: `FBAInboundV0:` Calling `->dto()`  on `getShipments` response throws `Argument #4 ($stateOrProvinceCode) not passed` exception
## Problem description:
When calling the `dto()` function on the response of the `FBAInboundV0` method, the error given below is thrown. `->json()` works.

## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
 ArgumentCountError 

  SellingPartnerApi\Seller\FBAInboundV0\Dto\Address::__construct(): Argument #4 ($stateOrProvinceCode) not passed

  at vendor/jlevers/selling-partner-api/src/Seller/FBAInboundV0/Dto/Address.php:34
     30▕      * If postal codes are used in your marketplace, we recommended that you include one with your request. This helps Amazon select the most appropriate Amazon fulfillment center for the inbound shipment plan.
     31▕      * @param  ?string  $addressLine2  Additional street address information, if required.
     32▕      * @param  ?string  $districtOrCounty  The district or county.
     33▕      */
  ➜  34▕     public function __construct(
     35▕         public readonly string $name,
     36▕         public readonly string $addressLine1,
     37▕         public readonly string $city,
     38▕         public readonly string $stateOrProvinceCode,
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
$response = $this->service->getFBAInboundApi()->getShipments(self::QUERY_TYPE, $marketplace, null, $unclosedShipmentIds)->dto();

```

### PR DESCRIPTION
**Pull request by dpash**
Data fetched from Amazon for shipments can be missing values. This results in deserialisation errors when Amazon returns data with those fields missing.

Fixes #703

### CODE REVIEW

**Comment by dpash** [comment]
Ideally we would have a separate Address types for requests and responses, but given FBA Inbound v0 is deprecated to be removed at the end of the year, I don't think it's worth implementing

**Comment by dpash** [comment]
I've added an additional field in the GetShipments call that's marked as required, but missing in response from Amazon

**Comment by jlevers** [comment]
Is the `AreCasesRequired` field always missing from the `GetShipments` call? If so, we could remove it entirely.

**Comment by dpash** [comment]
I don't have enough data to say for certain yet. 

I've updated the PR to resolve conflicts

**Pull request merged**
