### PR TITLE
Fix report download & downloadStream

### PR DESCRIPTION
**Pull request by widdydev**
This is the PR that fixes the [issue](https://github.com/jlevers/selling-partner-api/issues/559).

### CODE REVIEW

**Comment by jlevers** [comment]
@widdydev, thanks for the PR. My concern with this fix is, what if Amazon sends a report that is actually GZipped? Won't this prevent it from being unzipped?

**Comment by widdydev** [comment]
> @widdydev, thanks for the PR. My concern with this fix is, what if Amazon sends a report that is actually GZipped? Won't this prevent it from being unzipped?

So with `'decode_content' => false` we make sure that the GuzzleHttp client does not automatically decode the response and leaves it as it is. 
This means that we still would need to manually decode the response. And that's how it's implemented anyway. (That part with the `gzdecode` method).

You could actually confirm this by setting up a minimal example with a webserver serving - 1. a gzipped file and 2. an uncompressed file.
By using the GuzzleHttp client with the decode_content false option you'll receive the uncompressed file and be able to process it further. And for gzipped files it's necessary to call the gzdecode method in order to get the actual file contents.

**Comment by jlevers** [comment]
Ah, and because the issue is that Amazon is sending a response header indicating that the report file is gzipped when it isn't, not because the `compressionAlgo` key in the response body is incorrect. That makes sense, thanks.

**Comment by jlevers** [comment]
Closing this because Amazon fixed the upstream issue.

**Pull request closed without merging**
