### PR TITLE
Deserializes.php broke if the type is an DateTimeInterface due to only checking for classes and not interfaces

### PR DESCRIPTION
**Pull request by KhorneHoly**
Deserialization broke while creating the DTO from the SellingPartnerApi\Seller\ReportsV20210630\Responses\Report class, since the dates all are of the type DateTimeInterface.

### CODE REVIEW

**Comment by jlevers** [comment]
Couple minor comments, but looks good! Thanks for catching this. The reason for the Zulu format comment is that we changed the format in #699, too.

**Comment by KhorneHoly** [comment]
> Couple minor comments, but looks good! Thanks for catching this. The reason for the Zulu format comment is that we changed the format in #699, too.

Hi, thanks for the replay. You said something about minor comments, but I wasn't able to find anything. Am I missing something? Hit me up if there's need to change.

**Comment by jlevers** [comment]
Whoops, sorry...I hadn't clicked "Submit review." Should be visible now.

**Comment by KhorneHoly** [comment]
> Whoops, sorry...I hadn't clicked "Submit review." Should be visible now.

No worries, I've pushed a new commit with the respective changes. Also updated the exception message.

**Pull request merged**
