### PR TITLE
Update OrdersV0Api.php to fix RegulatedInfo requests

### PR DESCRIPTION
**Pull request by CaptainClueless**
Fix RegulatedInfo to sign requests correctly as the endpoint requires RDT

### CODE REVIEW

**Comment by CaptainClueless** [comment]
I appreciate there will not be many people using this endpoint, however it is a requirement for the integration I have

Without this fix, the endpoint returns that I am not authorised. With it, I get the data back successfully.

I appreciate someone looking at this pull request at their earliest convenience. Thanks

**Comment by da-mask** [comment]
Reviews have gone pretty quiet, hey @CaptainClueless ? I've got a similar pr (#638 ), but I can see I might have a long wait ahead of me..

**Comment by jlevers** [comment]
@da-mask sorry for the radio silence – I've been working on v6 of the library which will resolve a lot of the recent bug reports, but as a result I haven't had time to review PRs or respond to bug reports. You can track progress on that version of the lib on the v6 branch.

**Comment by jlevers** [comment]
This is fixed in `v6`.

**Pull request closed without merging**
