### PR TITLE
Regenerate library after schema caching fix

### PR DESCRIPTION
**Pull request by dpash**
Now we've fixed the schema caching, we need to regenerate the library

### CODE REVIEW

**Comment by dpash** [comment]
This PR doesn't include the schema loop detection fix, as I think there's an unintended breakage in another part of the library, so I'll create a separate PR for that

**Comment by jlevers** [comment]
The changes to `Links` and `Embedded` in both `Solicitations` and `Messaging` should be removed from this PR...those changes are a side effect of the caching changes – the new versions of `Links` and `Embedded` aren't quite right, but neither were their previous versions. This is a bug that I remember finding but forgot to document – when there are multiple inline schemas with the same names (as there are in `Solicitations` and `Messaging`, if you look for `_links` and `_embedded`), the autogenerated code for those inline schemas overwrites itself.

We need some way to distinguish different inline schemas with the same property name. Inline schemas are added to the `components.schemas` list here:

https://github.com/highsidelabs/saloon-sdk-generator/blob/eac6039b9fe854586a494752f1eb346d3ccdf5a2/src/Normalizers/OpenApiNormalizer.php#L235-L242

Probably the easiest option is to check if the schema already exists and add a number to its name if so. I'll open a separate issue for this.

**Comment by jlevers** [comment]
Resolved my last comment in 496e7edb2c659168f8a6022380f0f53029736b0e.

**Comment by jlevers** [comment]
@dpash I just merged these changes into main myself so that I can release v7 :)

**Pull request closed without merging**
