### PR TITLE
Enable simple saving of report documents

### PR DESCRIPTION
**Pull request by gravitiq-cm**
Added downloadToFile() method to enable saving files with minimal resource usage (contents are not parsed in transit). Some of the reports are Gb in size so we want to download them first and process them later.

### CODE REVIEW

**Comment by jlevers** [comment]
hey @gravitiq-cm thanks for the PR!

i actually would like to make the primary `download()` function work this way. i built the parsing the way i did because of some legal constraints on the SP API that are no longer there. would you be willing to rework this PR to integrate your changes into the `Document::download()` method? if the user doesn't actually want to save the raw file, then it can be saved to a temp file. otherwise, we can use your logic for saving to a user-specified file.

seems like the download function would need one new param: `string $saveToPath = null`. if it's not null, save the raw file to that path, and then continue with the rest of the existing method. does that sound sensible to you?

**Comment by gravitiq-cm** [comment]
Kind of busy at the moment, but I will look into this when I get a chance!

**Comment by quazardous** [comment]
FYI I think it's covered by #348 (a file is basically a stream).

**Comment by jlevers** [comment]
Closing due to @quazardous comment above (#348 has been merged).

**Pull request closed without merging**
