### PR TITLE
Update PrepInstruction.php

### PR DESCRIPTION
**Pull request by spire-mike**
Account for new 'ShipsInProductPackaging' prep instruction value.

https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#prepinstruction

### CODE REVIEW

**Comment by jlevers** [comment]
This should be fixed in `v6`, since enums in DTOs have been fully eliminated.

**Comment by spire-mike** [comment]
Thanks @jlevers - and thanks for maintaining this package! The update is working great.

Strangely, after upgrading to v6, I kept receiving an error that `Class Composer\Semver\VersionParser not found`. I rebuilt all my docker images, updating composer, nothing worked. It only worked after I required `"composer/semver"` in my own `composer.json` file, which is confusing because you already have it included in your file. So, I am not quite sure why that is necessary, but just thought I would ask if you had any idea.

**Comment by jlevers** [comment]
That was an issue with 6.0.0 and 6.0.1, where I had some packages set as dev dependencies that should have been regular dependencies. If you rebuild your container with the latest version of the library (6.0.4) and remove `composer/semver` from your `composer.json` that problem should go away.

**Comment by spire-mike** [comment]
Thanks @jlevers - I don't know why but `composer require jlevers/selling-partner-api` keeps resulting in `6.0.1` being downloaded.

**Comment by spire-mike** [comment]
Oh interesting, it might have to do with the version of an illuminate\support package in the project:

```
> sail composer require jlevers/selling-partner-api:6.0.4
./composer.json has been updated
Running composer update jlevers/selling-partner-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jlevers/selling-partner-api 6.0.4 -> satisfiable by jlevers/selling-partner-api[6.0.4].
    - jlevers/selling-partner-api 6.0.4 requires illuminate/support ^10.48 -> found illuminate/support[v10.48.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by jlevers** [comment]
Ah, interesting. What happens if you do `composer require -W jlevers/selling-partner-api:6.0.4`? There was a reason I required the version of `illuminate/support` that I did, but I forget what it was (classic). #676 is related to this too.

**Comment by spire-mike** [comment]
I still get the exact same error with the `-W` option. I'm using Laravel 9.52.16. For now I will just continue to include `composer/semver` myself. Maybe the issue will resolve itself after I upgrade to Laravel 10 or 11, which I plan to do soon.

**Comment by spire-mike** [comment]
Just FYI - upgrading to Laravel 10 fixed the issue. After upgrading laravel then `composer require jlevers/selling-partner-api`, the proper version 6.0.4 was installed.

**Pull request closed without merging**
