### PR TITLE
Update ShippingService.php

### PR DESCRIPTION
**Pull request by simonsolutions**
RequiresAdditionalSellerInputs is not always present in response, so allow nulled value

### CODE REVIEW

**Comment by KhorneHoly** [comment]
You edited a file that is auto generated. Have a look at this pull request: https://github.com/jlevers/selling-partner-api/pull/741
I've had a similar issue with a different class. You should add the change to the `modifications.json´ and then regenerate the files.

It's explained in the [contributing.md](https://github.com/jlevers/selling-partner-api/blob/main/CONTRIBUTING.md). 
Else your change would be revoked with the next generation process.

**Comment by simonsolutions** [comment]
Thank you @KhorneHoly for stating out that dependency. I changed like in your PR both json files as well. Hope the change is complete in that way?!

**Review by jlevers — APPROVED** [review]

**Comment by simonsolutions** [comment]
In which configuration do you run these commands, within my project the console command is not found and on a separate folder for the repo the autoload is not found.

**Comment by jlevers** [comment]
Are you in the root project directory for your fork of this repo when you run the commands?

**Comment by simonsolutions** [comment]
I tried both, my project root and the fork's root directory

**Comment by jlevers** [comment]
Can you show me the error you're getting?

**Comment by simonsolutions** [comment]
In my project root (this library added)

`
 There are no commands defined in the "schema" namespace.

  Did you mean this?
      doctrine:schema
`


and in the library's root:

`
PHP Warning:  require(/xxxxx/vendor/jlevers/selling-partner-api/bin/../vendor/autoload.php): Failed to open stream: No such file or directory in /xxxxx/vendor/jlevers/selling-partner-api/bin/console on line 3

Warning: require(/xxxxx/vendor/jlevers/selling-partner-api/bin/../vendor/autoload.php): Failed to open stream: No such file or directory in /xxxxx/vendor/jlevers/selling-partner-api/bin/console on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '/xxxxx/vendor/jlevers/selling-partner-api/bin/../vendor/autoload.php' (include_path='.:/opt/homebrew/Cellar/php/8.3.9/share/php/pear') in /xxxxx/vendor/jlevers/selling-partner-api/bin/console:3
Stack trace:
#0 {main}
  thrown in /xxxxx/vendor/jlevers/selling-partner-api/bin/console on line 3

Fatal error: Uncaught Error: Failed opening required '/xxxxx/vendor/jlevers/selling-partner-api/bin/../vendor/autoload.php' (include_path='.:/opt/homebrew/Cellar/php/8.3.9/share/php/pear') in /xxxxx/vendor/jlevers/selling-partner-api/bin/console:3
Stack trace:
#0 {main}
  thrown in /xxxxx/vendor/jlevers/selling-partner-api/bin/console on line 3
`

**Comment by jlevers** [comment]
It looks like you're trying to run the command from inside this library's folder in the `vendor/` directory of your project. You need to actually clone this repository, install the dependencies, and make changes there. Trying to contribute to the library from inside the `vendor/` folder of your project is not going to work.

Also, without doing that, you can't run the tests, linter, etc, which means that you can't fully check that your changes are valid before you commit them. There's more details on how to contribute in the [contributor guide](https://github.com/jlevers/selling-partner-api/blob/main/CONTRIBUTING.md).

**Comment by jlevers** [comment]
I tested this myself. Merging.

**Pull request merged**
