### PR TITLE
Make text/plain file downloadable

### PR DESCRIPTION
**Pull request by Ludofloria**
When using the UPLOAD_VAT_INVOICE, the Amazon API gives a result_feed_document_id that is a plain text file, holding this kind of information :

```
Feed Processing Summary:
        Number of records processed             1
        Number of records successful            0

original-record-number  sku     error-code      error-type      error-message
1               12345   Error   Please provide metadata:shippingid or metadata:orderid,metadata:invoicenumber,metadata:totalamount,metadata:totalvatamount
```

### CODE REVIEW

**Comment by jlevers** [comment]
Hey @Ludofloria, thanks for the PR!

I'm pretty sure that that style of file is actually a tab-separated-values file, based on how it's formatted -- it's just that the first 4 lines are structured strangely. If you look at the data starting on line 4, it's a list of column headers followed by rows (or in this case, just one row) of values.

**Comment by Ludofloria** [comment]
Indeed :)
But when using the tab separated value contentType, the parser fails ;)
Also, this PR is with an old version, which doesn't have the ContentTypes.php file ^^

**Comment by jlevers** [comment]
Forgot about the parsing problem, my bad. I think the correct solution here is to have the parser behave slightly differently when parsing feed result documents, but still treating them like tab files.

In your experience, does every feed result doc have 4 lines before the actual headers? If so, this is a pretty straightforward update. I tried to test/implement the parser update myself, but for some reason I'm getting a `400 InvalidInput` error on every feed I try to upload, so I don't have any testing data.

**Comment by jlevers** [comment]
The problem this PR is addressing should be fixed in `v3.0.2`. Give it a try and let me know if you run into any issues :)

**Comment by Ludofloria** [comment]
Sorry, I didn't get the mail notifications...

It seems that the FeedResultDoc have those 4 lines of "headers" text.

i'll try your latest changes ;)

**Comment by Cyniade** [comment]
Hello @Ludofloria ,

Sorry to ping you on this, but I have problem with upload of VAT invoice on Sp-API.

I always have the error : 
"Please provide metadata:shippingid or metadata:orderid,metadata:invoicenumber,metadata:totalamount,metadata:totalvatamount"

I'm passing a correct string to setFeedOptions() etc.

Did manage to upload pdf with this library ? 
Thanks.

**Comment by Ludofloria** [comment]
Hello @Cyniade !

I successfully managed to upload invoice PDFs with the SP-API.

First, you'd need to create a ConfigurationOptions that will holds your SP-API Credentials 👍 
```php
$configurationOptions = new ConfigurationOptions(
	"YourLWAClientID", // LWA Client ID 
	"YourLWAClientSecret", // LWA client secret
	"TheRefreshToken", // Refresh token
	"YourAWSAccessKey", // AWS access key ID
	"YourAWSSecretKey", // AWS secret access key
	"eu-west-1", // SP API AWS region
	"https://sellingpartnerapi-eu.amazon.com", // SP API endpoint. I'm in the EU so I use the EU endpoint
);

$config = new Configuration($configurationOptions);
```

Then, you use this to create a `FeedsApi`:

```php
$apiInstance = new Api\FeedsApi($config);
$docSpecs = new Feeds\CreateFeedDocumentSpecification([
	'content_type' => ContentType::PDF,
]);
```

You then create a FeedDocument:

```php
$feedInfos = null;
try {
	$result = $apiInstance->createFeedDocument($docSpecs);
	$feedInfos = $result->getPayload();
	
	echo "We created the Feed Document ! Now, let's upload the invoice\n";
	echo "The document ID is {$feedInfos->getFeedDocumentId()}\n";
} catch (Exception $e) {
	die('Exception when calling FeedsApi->createFeedDocument : ' . $e->getMessage() . PHP_EOL);
}
```

And then you can upload your PDF file:

```php
try {
	echo "Uploading the PDF file\n";
	$doc = new Document($feedInfos, ContentType::PDF);
	$doc->upload(file_get_contents("/path/to/your/file.pdf"));
} catch (Exception $e) {
	echo ("Exception when calling Document->upload :\n" . $e->getMessage() . PHP_EOL);
}
```

Finally, you must link the uploaded PDF to your Amazon Order. To do so, create a `FeedSpecification`:

```
$body = new \SellingPartnerApi\Model\Feeds\CreateFeedSpecification([
	'feed_type' => 'UPLOAD_VAT_INVOICE',
	'marketplace_ids' => ["A13V1IB3VIYZZH"], // This is the FR Amazon Marketplace ID
	'input_feed_document_id' => $feedInfos->getFeedDocumentId(),
	'feed_options' => [
		'metadata:Documentype' => 'Invoice',
		'metadata:InvoiceNumber' => "$YourOwnInvoiceNumber",
		'metadata:OrderId' => "$YourAmazonOrderNumber", // Should have the NNN-NNNNNNN-NNNNNNN format
		]
	]
);

try {
	echo "Linking the PDF uploaded to the order\n";
	$result = $apiInstance->createFeed($body);
	// This is to wait for Amazon to process our request
	if($waitForProcessing) {
		echo "Waiting for processing\n";
		do {
			$status = $apiInstance->getFeed($result->getPayload()->getFeedId());
			if ($status->getPayload()->getProcessingStatus() !== "DONE") {
				for($i = 0 ; $i < 10 ; $i++) {
					echo ".";
					sleep(1);
				}
			}
		} while($status->getPayload()->getProcessingStatus() !== "DONE");
		echo "\n";
		
		$docInfos = $apiInstance->getFeedDocument($status->getPayload()->getResultFeedDocumentId());
		
		$doc = new Document($docInfos->getPayload(), ContentType::TXT);
		echo "Results of the processing :\n";
		print_r($doc->download());
	}
} catch (Exception $e) {
	echo 'Exception when calling FeedsApi->createFeed: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by Cyniade** [comment]
> 

Hello @Ludofloria  !
Thank you for this wonderful answer. 😍 

Actually I figured out what was wrong in SP-Api doc' from Amazon.
It was the part regarding key for feedOptions :)

I forgot to make an answer with the "correct" way to upload invoices with library.

Again, a big thanks for this answer, it will be useful for anyone that have the same problem !

**Comment by Ludofloria** [comment]
I think I should make a PR to add this stuff into the Wiki, it will get lost here ^^

**Comment by cottton** [comment]
Just run into the same problem and would suggest to auto-format the key-value pairs,
OR at least give an example that can be found (in code and|or git).

Also:
at https://developer-docs.amazon.com/sp-api/docs/option-3-upload-invoices-through-sp-api-or-seller-central
its said

    feedOptions.put("metadata:OrderId", "XXX-XXXXXXX-XXXXXXX");
    feedOptions.put("metadata:TotalAmount", String.format(TOTALAMMOUNT));
    feedOptions.put("metadata:TotalVATAmount", String.format(TOTALVATAMMOUNT));
    feedOptions.put("metadata:InvoiceNumber", INVOICE_NUMBER);
    String options = feedOptions.entrySet().stream()
    .map(e -\> String.format("%s=%s", e.getKey(), e.getValue()))
    .collect(Collectors.joining(";"));

which would be 

    // Usual key value pairs.
    $options = [
        'OrderId' => "XXX-XXXXXXX-XXXXXXX",
        'TotalAmount' => "1.19",
        'TotalVATAmount' => "0.19",
        'InvoiceNumber' => 123456789,
    ];
    // Format to feed options as of amazon feed docu.
    $strings = [];
    foreach($options as $key => $value){
        $strings[] = 'metadata:'.strtolower($key)."=".trim($value);
    }
    $options = implode(";", $strings);

**My question is**: does this lib do implode|join the value strings by `;` ?
Because in the working example above @Ludofloria did not join them by ``;`.

**Pull request closed without merging**
